<a href="https://colab.research.google.com/github/TranQuocHuy83/mlops_training---module01---HuyTran-/blob/main/01_tensor_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Exercise 1: Tensor Creation
PyTorch Fundamentals - Module 1

This exercise covers:
- Creating tensors from different sources
- Understanding tensor attributes
- Creating tensors with specific values

PyTorch 2.0 Note: All code in this file is compatible with PyTorch 2.0.
See Exercise 5 for PyTorch 2.0 device management patterns.
"""
import torch
import numpy as np

# ============================================
# Part 1: Creating Tensors from Data
# ============================================

In [ ]:
print("=" * 60)
print("Part 1: Creating Tensors from Data")
print("=" * 60)

Part 1: Creating Tensors from Data


In [ ]:
# TODO: Create a scalar tensor (0-dimensional)
scalar = torch.tensor(7)
print(f"Scalar: {scalar}")
print(f"Scalar ndim: {scalar.ndim}")

Scalar: 7
Scalar ndim: 0


In [ ]:
# TODO: Create a vector tensor (1-dimensional)
vector = torch.tensor([1, 2, 3, 4, 5])
print(f"\nVector: {vector}")
print(f"Vector shape: {vector.shape}")


Vector: tensor([1, 2, 3, 4, 5])
Vector shape: torch.Size([5])


In [ ]:
# TODO: Create a matrix tensor (2-dimensional)
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"\nMatrix:\n{matrix}")
print(f"Matrix shape: {matrix.shape}")
print(f"Matrix ndim: {matrix.ndim}")


Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix shape: torch.Size([2, 3])
Matrix ndim: 2


In [ ]:
# TODO: Create a 3D tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"\n3D Tensor:\n{tensor_3d}")
print(f"3D Tensor shape: {tensor_3d.shape}")
print(f"3D Tensor ndim: {tensor_3d.ndim}")


3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3D Tensor shape: torch.Size([2, 2, 2])
3D Tensor ndim: 3


# ============================================
# Part 2: Creating Tensors with Specific Values
# ============================================

In [ ]:
print("\n" + "=" * 60)
print("Part 2: Creating Tensors with Specific Values")
print("=" * 60)


Part 2: Creating Tensors with Specific Values


In [ ]:
# TODO: Create a tensor filled with zeros
zeros = torch.zeros(3, 4)
print(f"Zeros (3x4):\n{zeros}")

Zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# TODO: Create a tensor filled with ones
ones = torch.ones(2, 3)
print(f"Ones (2x3):\n{ones}")

Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# TODO: Create a tensor filled with a specific value
full = torch.full((3, 4), 5)
print(f"Full with 7s (2x3):\n{full}")

Full with 7s (2x3):
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [ ]:
# TODO: Create identity matrix
identity = torch.eye(4)
print(f"Identity matrix (4x4):\n{identity}")

Identity matrix (4x4):
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [ ]:
# TODO: Create a tensor with values from 0 to 9
range_tensor = torch.arange(0, 10)
print(f"Range (0-9):\n{range_tensor}")

Range (0-9):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# TODO: Create evenly spaced values
linspace = torch.linspace(0, 10, steps=5)
print(f"Linspace (0-10, 5 steps):\n{linspace}")

Linspace (0-10, 5 steps):
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


# ============================================
# Part 3: Creating Random Tensors
# ============================================

In [ ]:
print("\n" + "=" * 60)
print("Part 3: Creating Random Tensors")
print("=" * 60)


Part 3: Creating Random Tensors


In [ ]:
# TODO: Set random seed for reproducibility
torch.manual_seed(42)

In [ ]:
# TODO: Create random tensor from uniform distribution [0, 1)
rand_uniform = torch.rand(3, 4)
print(f"Random uniform (3x4):\n{rand_uniform}")

Random uniform (3x4):
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [ ]:
# TODO: Create random tensor from normal distribution
rand_normal = torch.randn(2, 3)
print(f"Random normal (2x3):\n{rand_normal}")

Random normal (2x3):
tensor([[ 0.1498, -0.2089, -0.3870],
        [ 0.9912,  0.4679, -0.2049]])


In [ ]:
# TODO: Create random integers
rand_int = torch.randint(low=0, high=10, size=(3, 3))
print(f"Random integers (0-9, 3x3):\n{rand_int}")

Random integers (0-9, 3x3):
tensor([[0, 0, 1],
        [3, 0, 1],
        [1, 7, 9]])


# ============================================
# Part 4: Working with NumPy
# ============================================

In [ ]:
print("\n" + "=" * 60)
print("Part 4: Working with NumPy")
print("=" * 60)


Part 4: Working with NumPy


In [ ]:
# TODO: Create a NumPy array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"NumPy array:\n{np_array}")

NumPy array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# TODO: Convert NumPy array to PyTorch tensor
tensor_from_np = torch.from_numpy(np_array)
print(f"Tensor from NumPy:\n{tensor_from_np}")

Tensor from NumPy:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# TODO: Convert PyTorch tensor to NumPy array
np_from_tensor = tensor_from_np.numpy()
print(f"NumPy from tensor:\n{np_from_tensor}")

NumPy from tensor:
[[1 2 3]
 [4 5 6]]


# ============================================
# Part 5: Tensor Attributes
# ============================================

In [ ]:
print("\n" + "=" * 60)
print("Part 5: Tensor Attributes")
print("=" * 60)


Part 5: Tensor Attributes


In [ ]:
tensor = torch.randn(2, 3, 4)

# TODO: Print tensor shape
print(f"Shape: {tensor.shape}")

# TODO: Print tensor data type
print(f"Dtype: {tensor.dtype}")

# TODO: Print tensor device
print(f"Device: {tensor.device}")

# TODO: Print number of dimensions
print(f"Number of dimensions: {tensor.ndim}")

# TODO: Print total number of elements
print(f"Total elements: {tensor.numel()}")

Shape: torch.Size([2, 3, 4])
Dtype: torch.float32
Device: cpu
Number of dimensions: 3
Total elements: 24


In [ ]:
print(tensor)

tensor([[[ 0.5362,  0.5246,  1.1412,  0.0516],
         [ 0.7281, -0.7106, -0.6021,  0.9604],
         [-0.3165,  0.5886, -0.8905,  0.4098]],

        [[-1.4570, -0.1023, -0.5992,  0.4771],
         [-0.1693,  0.2332,  4.0356,  1.2795],
         [-0.0127,  0.2408,  0.1325,  0.7642]]])


# ============================================
# Exercises
# ============================================

In [ ]:
print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)


Exercises


In [ ]:
# Exercise 1: Create a 4x4 tensor filled with the value 3.14
print("\nExercise 1: Create a 4x4 tensor filled with 3.14")
# Your code here
ex1 = torch.full((4,4),3.14)
print(ex1)


Exercise 1: Create a 4x4 tensor filled with 3.14
tensor([[3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400]])


In [ ]:
# Exercise 2: Create a random tensor of shape (5, 5) with values between 0 and 1
print("\nExercise 2: Create random 5x5 tensor [0, 1)")
# Your code here
ex2 = torch.rand(5,5)
print(ex2)


Exercise 2: Create random 5x5 tensor [0, 1)
tensor([[0.1568, 0.2083, 0.3289, 0.1054, 0.9192],
        [0.4008, 0.9302, 0.6558, 0.0766, 0.8460],
        [0.3624, 0.3083, 0.0850, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897, 0.8712, 0.1330],
        [0.4137, 0.6044, 0.7581, 0.9037, 0.9555]])


In [ ]:
# Exercise 3: Create a tensor with values from 10 to 50 (exclusive) with step 5
print("\nExercise 3: Range from 10 to 50 with step 5")
# Your code here
ex3 = torch.arange(10,50,5)
print(ex3)


Exercise 3: Range from 10 to 50 with step 5
tensor([10, 15, 20, 25, 30, 35, 40, 45])


In [ ]:
# Exercise 4: Create a 3D tensor of shape (2, 3, 4) filled with ones
print("\nExercise 4: Create 3D tensor (2, 3, 4) of ones")
# Your code here
ex4 = torch.ones(2,3,4)
print(ex4)


Exercise 4: Create 3D tensor (2, 3, 4) of ones
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [ ]:
# Exercise 5: Check if a GPU is available and create a tensor on it if possible
print("\nExercise 5: Create tensor on GPU if available")
# Your code here
device = "cuda" if torch.cuda.is_available() else "cpu"
ex5 = torch.tensor([1,2,3], device= device)
print(f"Using device: {device}")
print(ex5)


Exercise 5: Create tensor on GPU if available
Using device: cpu
tensor([1, 2, 3])


In [ ]:
# PyTorch 2.0+ Example: Using torch.set_default_device()
# This is available in PyTorch 2.0+ for cleaner device management
if torch.cuda.is_available():
    print("\nPyTorch 2.0+ Device Management Example:")

    # Set CUDA as the default device
    torch.set_default_device('cuda')

    # All subsequent tensors are created on CUDA by default
    x_auto = torch.randn(2, 3)
    print(f"Auto-created on device: {x_auto.device}")

    # Reset to CPU
    torch.set_default_device('cpu')
    y_auto = torch.randn(2, 3)
    print(f"Reset to CPU device: {y_auto.device}")


print("\n" + "=" * 60)
print("Exercise 1 Complete!")
print("=" * 60)



Exercise 1 Complete!
