<a href="https://colab.research.google.com/github/TranQuocHuy83/mlops_training---module01---HuyTran-/blob/main/02_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
"""
Exercise 2: Tensor Operations
PyTorch Fundamentals - Module 1

This exercise covers:
- Basic arithmetic operations
- Matrix operations
- Reduction operations
- Comparison operations

PyTorch 2.0 Note: All operations in this file are compatible with PyTorch 2.0.
The @ operator for matrix multiplication is recommended for both PyTorch 1.x and 2.0.
"""

import torch

# ============================================
# Part 1: Basic Arithmetic Operations
# ============================================


In [3]:
# Set random seed for reproducibility
torch.manual_seed(42)

print("=" * 60)
print("Part 1: Basic Arithmetic Operations")
print("=" * 60)

Part 1: Basic Arithmetic Operations


In [4]:
# Create test tensors
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([5, 6, 7, 8], dtype=torch.float32)

print(f"x: {x}")
print(f"y: {y}")

x: tensor([1., 2., 3., 4.])
y: tensor([5., 6., 7., 8.])


In [5]:
# TODO: Addition
add_result = x + y
print(f"\nAddition (x + y): {add_result}")


Addition (x + y): tensor([ 6.,  8., 10., 12.])


In [6]:
# TODO: Subtraction
sub_result = x - y
print(f"Subtraction (x - y): {sub_result}")

Subtraction (x - y): tensor([-4., -4., -4., -4.])


In [7]:
# TODO: Element-wise multiplication
mul_result = x * y
print(f"Multiplication (x * y): {mul_result}")

Multiplication (x * y): tensor([ 5., 12., 21., 32.])


In [8]:
# TODO: Element-wise division
div_result = x / y
print(f"Division (x / y): {div_result}")

Division (x / y): tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [9]:
# TODO: Power
pow_result = x ** 2
print(f"Power (x^2): {pow_result}")

Power (x^2): tensor([ 1.,  4.,  9., 16.])


# ============================================
# Part 2: Matrix Operations
# ============================================

In [17]:
print("\n" + "=" * 60)
print("Part 2: Matrix Operations")
print("=" * 60)

# Create matrices
A = torch.randn(3, 4)
B = torch.randn(4, 5)

print(f"Matrix A shape: {A.shape}")
print(f"Matrix B shape: {B.shape}")


Part 2: Matrix Operations
Matrix A shape: torch.Size([3, 4])
Matrix B shape: torch.Size([4, 5])


In [24]:
# TODO: Matrix multiplication
matmul_result = A @ B
print(f"\nMatrix multiplication A @ B shape: {matmul_result.shape}\n")

# TODO: Transpose
A_T = A.T
print(A)
print(f"Matrix A shape: {A.shape}\n")
print(A_T)
print(f"Transpose of A shape: {A_T.shape}")


Matrix multiplication A @ B shape: torch.Size([3, 5])

tensor([[ 0.3183,  1.1330, -1.1635, -2.6641],
        [ 1.0122, -0.6236,  0.5438, -2.3363],
        [ 0.1034,  0.2514,  1.2446,  0.5263]])
Matrix A shape: torch.Size([3, 4])

tensor([[ 0.3183,  1.0122,  0.1034],
        [ 1.1330, -0.6236,  0.2514],
        [-1.1635,  0.5438,  1.2446],
        [-2.6641, -2.3363,  0.5263]])
Transpose of A shape: torch.Size([4, 3])


In [25]:
# TODO: Element-wise min/max
min_val = torch.min(A)
max_val = torch.max(A)
print(f"\nMin value in A: {min_val:.4f}")
print(f"Max value in A: {max_val:.4f}")


Min value in A: -2.6641
Max value in A: 1.2446


# ============================================
# Part 3: Reduction Operations
# ============================================

In [26]:
print("\n" + "=" * 60)
print("Part 3: Reduction Operations")
print("=" * 60)

# Create a 2D tensor
tensor = torch.randn(3, 4)
print(f"Tensor:\n{tensor}")


Part 3: Reduction Operations
Tensor:
tensor([[ 0.3471, -0.1014, -0.7543,  1.9346],
        [-1.2589, -0.3895,  0.5330, -0.2423],
        [ 0.6654,  0.9383,  0.0445,  1.1535]])


In [27]:
# TODO: Sum all elements
sum_all = torch.sum(tensor)
print(f"\nSum of all elements: {sum_all:.4f}")


Sum of all elements: 2.8699


In [28]:
# TODO: Sum along rows (dim=0)
sum_rows = torch.sum(tensor, dim=0)
print(f"Sum along rows: {sum_rows}")

Sum along rows: tensor([-0.2465,  0.4474, -0.1767,  2.8457])


In [29]:
# TODO: Sum along columns (dim=1)
sum_cols = torch.sum(tensor, dim=1)
print(f"Sum along columns: {sum_cols}")

Sum along columns: tensor([ 1.4260, -1.3578,  2.8017])


In [30]:
# TODO: Mean
mean_all = torch.mean(tensor)
print(f"\nMean of all elements: {mean_all:.4f}")


Mean of all elements: 0.2392


In [31]:
# TODO: Standard deviation
std_all = torch.std(tensor)
print(f"Standard deviation: {std_all:.4f}")

Standard deviation: 0.8786


# ============================================
# Part 4: Comparison Operations
# ============================================

In [32]:
print("\n" + "=" * 60)
print("Part 4: Comparison Operations")
print("=" * 60)

x = torch.tensor([1, 2, 3, 4, 5])
y = torch.tensor([2, 2, 4, 4, 6])

print(f"x: {x}")
print(f"y: {y}")


Part 4: Comparison Operations
x: tensor([1, 2, 3, 4, 5])
y: tensor([2, 2, 4, 4, 6])


In [33]:
# TODO: Element-wise comparison
eq_result = x == y
print(f"\nEqual (x == y): {eq_result}")


Equal (x == y): tensor([False,  True, False,  True, False])


In [34]:
gt_result = x > y
print(f"Greater than (x > y): {gt_result}")

Greater than (x > y): tensor([False, False, False, False, False])


In [35]:
lt_result = x < y
print(f"Less than (x < y): {lt_result}")

Less than (x < y): tensor([ True, False,  True, False,  True])


In [36]:
# TODO: Clamp values
clamped = torch.clamp(x, min=2, max=4)
print(f"\nClamp x to [2, 4]: {clamped}")


Clamp x to [2, 4]: tensor([2, 2, 3, 4, 4])


# ============================================
# Part 5: Broadcasting
# ============================================

In [43]:
print("\n" + "=" * 60)
print("Part 5: Broadcasting")
print("=" * 60)

# Create tensors with different shapes
x = torch.randn(3, 1)
y = torch.randn(1, 4)

print(f"x shape: {x.shape}")
print(f"y shape: {y.shape}")
# TODO: Broadcast addition
result = x + y
print(f"\nBroadcast result shape: {result.shape}")
print(f"Result:\n{result}")


Part 5: Broadcasting
x shape: torch.Size([3, 1])
y shape: torch.Size([1, 4])

Broadcast result shape: torch.Size([3, 4])
Result:
tensor([[-1.5839, -0.5238,  0.0322, -1.8677],
        [ 0.1877,  1.2478,  1.8038, -0.0961],
        [-1.4232, -0.3631,  0.1929, -1.7071]])


# ============================================
# Exercises
# ============================================

In [44]:
print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)


Exercises


In [46]:
# Exercise 1: Given two matrices A (4x3) and B (3x5), compute C = A @ B
print("\nExercise 1: Matrix multiplication")
A = torch.randn(4, 3)
B = torch.randn(3, 5)
# Compute C = A @ B
C = A @ B
print(A)
print(B)
print(C)


Exercise 1: Matrix multiplication
tensor([[ 1.0716, -0.2662,  1.0295],
        [ 0.1327,  1.8114, -1.0315],
        [ 1.1471, -0.3532, -0.3664],
        [ 0.0060, -0.9082, -0.3319]])
tensor([[-0.1818,  0.5765,  0.3052,  0.2078,  0.2062],
        [-0.4174,  1.3074,  2.8570, -1.4772, -0.0496],
        [ 1.1342, -0.5377, -0.3539,  0.9743,  0.4280]])
tensor([[ 1.0840e+00, -2.8382e-01, -7.9788e-01,  1.6190e+00,  6.7486e-01],
        [-1.9502e+00,  2.9994e+00,  5.5808e+00, -3.6534e+00, -5.0405e-01],
        [-4.7680e-01,  3.9667e-01, -5.2927e-01,  4.0300e-01,  9.7252e-02],
        [ 1.5378e-03, -1.0054e+00, -2.4755e+00,  1.0195e+00, -9.5754e-02]])


In [50]:
# Exercise 2: Normalize a tensor to have zero mean and unit variance
print("\nExercise 2: Normalize tensor")
tensor = torch.randn(100, 10)
# Normalize: (x - mean) / std
mean = torch.mean(tensor)
std = torch.std(tensor)
normalized = (tensor - mean) / std
print(normalized)
print(torch.mean(normalized))
print(torch.std(normalized))


Exercise 2: Normalize tensor
tensor([[-2.4899e-01, -6.7953e-01,  4.2981e-01, -9.0606e-01,  6.1204e-02,
          4.9512e-01, -5.0546e-01, -1.2329e+00,  1.7377e-01, -4.9242e-02],
        [-9.1482e-01,  1.1157e+00, -1.6365e+00, -3.6074e-01, -8.6251e-01,
          7.4070e-01, -5.1768e-01,  4.2195e-03, -6.7168e-01,  1.2507e+00],
        [-7.7420e-01, -1.0951e+00, -8.6099e-01,  6.7635e-01, -3.7963e-01,
          5.7221e-01, -7.5343e-01, -6.4708e-01, -1.5068e+00, -2.4812e-01],
        [ 1.8975e+00,  4.2127e-01, -4.9383e-01, -3.3311e-01,  1.0888e-01,
          5.8691e-01,  7.6395e-01,  1.9860e-01, -9.1116e-01,  1.8498e+00],
        [-3.2810e-01,  1.8001e-01, -1.9193e+00, -5.4806e-01, -6.7248e-01,
          2.1280e-01, -2.2294e-01,  1.1578e+00, -2.0511e-01,  1.5098e+00],
        [ 9.7364e-02,  2.6300e-01,  6.6243e-01, -2.0266e+00,  9.3555e-02,
         -6.2112e-01,  5.1289e-01, -1.3257e+00, -4.5154e-01, -7.0596e-01],
        [-1.4550e+00,  1.9939e+00, -1.3878e-01,  3.5397e-02,  1.1511e+00,
  

In [53]:
# Exercise 3: Find the indices of the top 3 values in a tensor
print("\nExercise 3: Find top 3 indices")
tensor = torch.randn(10)
# Find indices of top 3 values
top_3_indices = torch.topk(tensor, 3).indices
print(tensor)
print(top_3_indices)


Exercise 3: Find top 3 indices
tensor([-0.6613,  2.0240,  0.3266,  0.4447,  0.7277,  1.1330, -0.1021,  0.9791,
         0.1880,  0.3817])
tensor([1, 5, 7])


In [54]:
# Exercise 4: Implement softmax function
print("\nExercise 4: Implement softmax")
logits = torch.randn(2, 5)  # Batch of 2, 5 classes
# Implement: softmax(x) = exp(x) / sum(exp(x))
softmax = torch.exp(logits) / torch.sum(torch.exp(logits))
print(softmax)


Exercise 4: Implement softmax
tensor([[0.0534, 0.1410, 0.0274, 0.0447, 0.2010],
        [0.1397, 0.1620, 0.0139, 0.0228, 0.1941]])


In [59]:
# Exercise 5: Compute cosine similarity between two vectors
print("\nExercise 5: Cosine similarity")
v1 = torch.randn(10)
v2 = torch.randn(10)
# Compute cosine similarity: (v1 . v2) / (||v1|| * ||v2||)
print(v1)
print(v2)
cosine_similarity = torch.dot(v1, v2) / (torch.norm(v1) * torch.norm(v2))
print(f"Cosin Similarity {cosine_similarity}")


print("\n" + "=" * 60)
print("Exercise 2 Complete!")
print("=" * 60)


Exercise 5: Cosine similarity
tensor([-0.2460, -0.4367, -0.9273, -0.4265, -0.1204,  0.7827,  0.8690,  0.0953,
        -0.3192, -1.0225])
tensor([-0.1700, -0.1454, -0.4587,  0.4943,  0.7654,  0.8358, -0.0638,  0.4813,
        -0.0033,  1.5297])
Cosin Similarity -0.16888053715229034

Exercise 2 Complete!
