<a href="https://colab.research.google.com/github/TranQuocHuy83/mlops_training---module01---HuyTran-/blob/main/03_tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
Exercise 3: Tensor Manipulation
PyTorch Fundamentals - Module 1

This exercise covers:
- Reshaping tensors
- Indexing and slicing
- Transposing and permuting
- Squeezing and unsqueezing
- Concatenating and splitting tensors

PyTorch 2.0 Note: All manipulation operations are compatible with PyTorch 2.0.
See the device management section for torch.set_default_device() (PyTorch 2.0+ feature).
"""

import torch
# Set random seed for reproducibility
torch.manual_seed(42)

# ============================================
# Part 1: Reshaping
# ============================================

In [2]:
print("=" * 60)
print("Part 1: Reshaping Tensors")
print("=" * 60)

# Create a 1D tensor
x = torch.arange(12)
print(f"Original tensor: {x}")
print(f"Original shape: {x.shape}")
print(f"Original shape: {x.ndim}")

Part 1: Reshaping Tensors
Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])
Original shape: 1


In [3]:
# TODO: Reshape to 3x4
reshaped = x.reshape(3, 4)
print(f"\nReshaped to (3, 4):\n{reshaped}")
print(f"Original shape: {reshaped.shape}")
print(f"Original shape: {reshaped.ndim}")


Reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Original shape: torch.Size([3, 4])
Original shape: 2


In [4]:
# TODO: Reshape to 2x6
reshaped_2x6 = x.reshape(2, 6)
print(f"\nReshaped to (2, 6):\n{reshaped_2x6}")
print(f"Original shape: {reshaped_2x6.shape}")
print(f"Original shape: {reshaped_2x6.ndim}")


Reshaped to (2, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Original shape: torch.Size([2, 6])
Original shape: 2


In [5]:
# TODO: Flatten a 2D tensor
flat1 = reshaped.flatten()
print(f"\nFlattened: {flat1}")


Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [6]:
# TODO: Flatten a 2D tensor
flat2 = reshaped_2x6.flatten()
print(f"\nFlattened: {flat2}")


Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [7]:
# TODO: Reshape with view (only works on contiguous tensors)
viewed = reshaped.view(-1)  # -1 means infer dimension
print(f"\nViewed as 1D: {viewed}")


Viewed as 1D: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [8]:
T = torch.arange(12)
R = T.reshape(2, 2, 3)
R_V = reshaped.view(-1)
print(T)
print(R)
print(R_V)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


# ============================================
# Part 2: Squeeze and Unsqueeze
# ============================================

In [9]:
print("\n" + "=" * 60)
print("Part 2: Squeeze and Unsqueeze")
print("=" * 60)

# Create tensor with singleton dimensions
x = torch.randn(2, 1, 4, 1) #(batch, channel, height, width)
print(f"Original tensor:\n{x}")
print(f"Original dim: {x.dim}")
print(f"Original shape: {x.shape}")


Part 2: Squeeze and Unsqueeze
Original tensor:
tensor([[[[ 0.3367],
          [ 0.1288],
          [ 0.2345],
          [ 0.2303]]],


        [[[-1.1229],
          [-0.1863],
          [ 2.2082],
          [-0.6380]]]])
Original dim: <built-in method dim of Tensor object at 0x7b9b0df994f0>
Original shape: torch.Size([2, 1, 4, 1])


In [10]:
# TODO: Remove all singleton dimensions
squeezed = x.squeeze()
print(f"\nAfter squeeze:\n{squeezed}")
print(f"After squeeze: {squeezed.shape}")


After squeeze:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])
After squeeze: torch.Size([2, 4])


In [11]:
# TODO: Remove specific singleton dimension
squeezed_dim = x.squeeze(dim=1)
print(f"\nAfter squeeze(dim=1): {squeezed_dim}")
print(f"After squeeze(dim=1): {squeezed_dim.shape}")


After squeeze(dim=1): tensor([[[ 0.3367],
         [ 0.1288],
         [ 0.2345],
         [ 0.2303]],

        [[-1.1229],
         [-0.1863],
         [ 2.2082],
         [-0.6380]]])
After squeeze(dim=1): torch.Size([2, 4, 1])


In [13]:
# TODO: Add dimension at position 0
unsqueezed_0 = squeezed.unsqueeze(dim=0)
print(f"\nAfter unsqueeze(dim=0): {unsqueezed_0}")
print(f"\nAfter unsqueeze(dim=0): {unsqueezed_0.shape}")


After unsqueeze(dim=0): tensor([[[ 0.3367,  0.1288,  0.2345,  0.2303],
         [-1.1229, -0.1863,  2.2082, -0.6380]]])

After unsqueeze(dim=0): torch.Size([1, 2, 4])


In [15]:
# TODO: Add dimension at last position
unsqueezed_last = squeezed.unsqueeze(dim=-1)
print(f"\nAfter unsqueeze(dim=-1): {unsqueezed_last}")
print(f"After unsqueeze(dim=-1): {unsqueezed_last.shape}")


After unsqueeze(dim=-1): tensor([[[ 0.3367],
         [ 0.1288],
         [ 0.2345],
         [ 0.2303]],

        [[-1.1229],
         [-0.1863],
         [ 2.2082],
         [-0.6380]]])
After unsqueeze(dim=-1): torch.Size([2, 4, 1])


# ============================================
# Part 3: Transpose and Permute
# ============================================

In [23]:
print("\n" + "=" * 60)
print("Part 3: Transpose and Permute")
print("=" * 60)

# Create a 3D tensor
x = torch.randn(2, 3, 4)
print(f"Original shape: {x}")
print(f"Original shape: {x.shape}")


Part 3: Transpose and Permute
Original shape: tensor([[[-0.1593, -0.4249,  0.9442, -0.1849],
         [ 1.0608,  0.2083, -0.5778,  0.3255],
         [-0.0045,  1.6668,  0.1539, -1.0603]],

        [[-0.5727,  0.0836,  0.3999,  1.9892],
         [-0.0720, -0.9061, -2.0487, -1.0811],
         [ 0.0176,  0.0782,  0.1932,  0.4097]]])
Original shape: torch.Size([2, 3, 4])


In [24]:
# TODO: Transpose dimensions 0 and 1
transposed = torch.transpose(x, 0, 1)
print(f"After transpose(0, 1): {transposed}")
print(f"After transpose(0, 1): {transposed.shape}")

After transpose(0, 1): tensor([[[-0.1593, -0.4249,  0.9442, -0.1849],
         [-0.5727,  0.0836,  0.3999,  1.9892]],

        [[ 1.0608,  0.2083, -0.5778,  0.3255],
         [-0.0720, -0.9061, -2.0487, -1.0811]],

        [[-0.0045,  1.6668,  0.1539, -1.0603],
         [ 0.0176,  0.0782,  0.1932,  0.4097]]])
After transpose(0, 1): torch.Size([3, 2, 4])


In [25]:
# TODO: Permute all dimensions
permuted = x.permute(2, 0, 1)
print(f"After permute(2, 0, 1): {permuted}")
print(f"After permute(2, 0, 1): {permuted.shape}")

After permute(2, 0, 1): tensor([[[-0.1593,  1.0608, -0.0045],
         [-0.5727, -0.0720,  0.0176]],

        [[-0.4249,  0.2083,  1.6668],
         [ 0.0836, -0.9061,  0.0782]],

        [[ 0.9442, -0.5778,  0.1539],
         [ 0.3999, -2.0487,  0.1932]],

        [[-0.1849,  0.3255, -1.0603],
         [ 1.9892, -1.0811,  0.4097]]])
After permute(2, 0, 1): torch.Size([4, 2, 3])


In [26]:
# TODO: Matrix transpose for 2D tensor
matrix = torch.randn(3, 4)
print(f"\nMatrix shape: {matrix.shape}")
print(f"Matrix.T shape: {matrix.T.shape}")


Matrix shape: torch.Size([3, 4])
Matrix.T shape: torch.Size([4, 3])


# ============================================
# Part 4: Indexing and Slicing
# ============================================

In [27]:
print("\n" + "=" * 60)
print("Part 4: Indexing and Slicing")
print("=" * 60)

# Create a 2D tensor
x = torch.arange(20).reshape(4, 5)
print(f"Tensor:\n{x}")


Part 4: Indexing and Slicing
Tensor:
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


In [28]:
# TODO: Get element at position (1, 2)
element = x[1, 2]
print(f"\nElement at [1, 2]: {element}")


Element at [1, 2]: 7


In [35]:
# TODO: Get first row
first_row = x[0,:]
print(f"\nFirst row: {first_row}")


First row: tensor([0, 1, 2, 3, 4])


In [33]:
# TODO: Get last column
last_col = x[:, -1]
print(f"Last column: {last_col}")

Last column: tensor([ 4,  9, 14, 19])


In [36]:
# TODO: Get submatrix (rows 1-2, cols 2-4)
submatrix = x[1:3, 2:5]
print(f"\nSubmatrix [1:3, 2:5]:\n{submatrix}")


Submatrix [1:3, 2:5]:
tensor([[ 7,  8,  9],
        [12, 13, 14]])


In [37]:
# TODO: Boolean indexing
mask = x > 10
values = x[mask]
print(f"\nValues > 10: {values}")


Values > 10: tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])


In [ ]:



# ============================================
# Part 5: Concatenating and Splitting
# ============================================

print("\n" + "=" * 60)
print("Part 5: Concatenating and Splitting")
print("=" * 60)

# Create tensors to concatenate
x1 = torch.randn(2, 3)
x2 = torch.randn(2, 3)
x3 = torch.randn(2, 3)

print(f"x1 shape: {x1.shape}")
print(f"x2 shape: {x2.shape}")

# TODO: Stack along new dimension (dim=0)
stacked = torch.stack([x1, x2, x3], dim=0)
print(f"\nStacked along dim=0: {stacked.shape}")

# TODO: Concatenate along existing dimension (dim=0)
concat_dim0 = torch.cat([x1, x2, x3], dim=0)
print(f"Concatenated along dim=0: {concat_dim0.shape}")

# TODO: Split tensor into chunks
x = torch.randn(6, 4)
chunks = torch.chunk(x, chunks=3, dim=0)
print(f"\nSplit into 3 chunks along dim=0:")
for i, chunk in enumerate(chunks):
    print(f"  Chunk {i} shape: {chunk.shape}")

# TODO: Split at specific indices
split_sections = torch.split(x, [2, 4], dim=0)
print(f"\nSplit into sections of size [2, 4]:")
for i, section in enumerate(split_sections):
    print(f"  Section {i} shape: {section.shape}")


# ============================================
# Exercises
# ============================================

print("\n" + "=" * 60)
print("Exercises")
print("=" * 60)

# Exercise 1: Given a tensor of shape (64, 1, 28, 28), remove the singleton dimension
print("\nExercise 1: Remove singleton dimension")
x = torch.randn(64, 1, 28, 28)
# Your code here

# Exercise 2: Add a batch dimension to a single image tensor of shape (3, 224, 224)
print("\nExercise 2: Add batch dimension")
image = torch.randn(3, 224, 224)
# Your code here - should result in (1, 3, 224, 224)

# Exercise 3: Convert HWC format to CHW format
print("\nExercise 3: HWC to CHW conversion")
hwc_image = torch.randn(224, 224, 3)
# Your code here - should result in (3, 224, 224)

# Exercise 4: Extract the diagonal elements from a square matrix
print("\nExercise 4: Extract diagonal")
matrix = torch.randn(5, 5)
# Your code here

# Exercise 5: Create a batch of 10 random images and stack them
print("\nExercise 5: Stack images into batch")
images = [torch.randn(3, 224, 224) for _ in range(10)]
# Your code here - should result in (10, 3, 224, 224)


print("\n" + "=" * 60)
print("Exercise 3 Complete!")
print("=" * 60)